### ISSUE TITLE
Add support for RSS/Atom feeds for PWA with proxy url fetch

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-chat#13]
RSS Feeds won't work from a standard web page without support of a proxy web server because of cross-domain permissions and policies. In other words, the JavaScript in the web page from your web site cannot load an RSS/Atom file from a web site with a different domain. 
See https://github.com/igniterealtime/Pade/issues/192

Provide a proxy URL fetch service that can fetch any RSS/Atom feed URL and bypass cross-domain issues for all web apps hosted in the chat api web server.

**Comment by deleolajide** [comment]
This is now available in version 0.9.5 Release 5

![image](https://user-images.githubusercontent.com/110731/60434171-76e18380-9bfe-11e9-8c03-0f4ff760e5d6.png)

**Comment by jac110** [comment]
Waow, that was fast !
Many thanks for the solution.
